### ISSUE TITLE
Possible to add a license to this? 

### ISSUE THREAD

**Issue by brianwilt** [efstathiosntonas/tiktok-clone#3]
Would it be possible to add a license to this, like MIT or Apache? Would love to build off of it. Thank you!

**Comment by efstathiosntonas** [comment]
Hi @brianwilt, will add it later today! I can add you as a collaborator if you’d like to.

**Comment by brianwilt** [comment]
You’re awesome ! Thank you.

I meant that I wanted to use this template to build an app to be clear.
Thanks !

**Comment by efstathiosntonas** [comment]
Ok no problem!

**Comment by efstathiosntonas** [comment]
hi @brianwilt, just added license, sorry for the delay! Happy coding :D

**Comment by brianwilt** [comment]
You’re awesome thanks so much !
